import type { DeliveryMode } from "@/lib/db";

export type GroupingMode =
  | "flat"
  | "feature"
  | "source"
  | "layer"
  | "priority"
  | "story"
  | "methodology";
export type StatusFilter = "all" | "todo" | "in_progress" | "done";
export type PriorityFilter = "all" | "must" | "should" | "could" | "wont";
export type SourceFilter = "all" | "manual" | string;

export interface TaskSummary {
  total: number;
  done: number;
  inProgress: number;
  manual: number;
  autoGenerated: number;
  imported: number;
  mustHave: number;
}

export interface TaskReconciliationSummary {
  matched: number;
  unmatched: number;
}

export interface DeliveryModeMeta {
  mode: DeliveryMode;
  label: string;
}
