FROM oven/bun:alpine
WORKDIR /app

# Required for Next.js telemetry and sharp
RUN apk add --no-cache libc6-compat

COPY package.json bun.lock* ./

RUN bun install

COPY . .

EXPOSE 3000
CMD ["bun", "run", "dev"]
