"use client";

import { TaskSummary } from "../types";

function SummaryCard({
  label,
  value,
  helper,
  testId,
}: {
  label: string;
  value: string | number;
  helper: string;
  testId?: string;
}) {
  return (
    <div
      className="rounded-xl border border-border/60 bg-background/50 px-3 py-2 shadow-sm flex items-center justify-between gap-4"
      data-testid={testId}
    >
      <div className="min-w-0">
        <p className="text-readable-2xs uppercase tracking-widest text-muted-foreground font-semibold truncate">
          {label}
        </p>
        <p className="mt-0.5 text-readable-2xs text-muted-foreground/60 font-medium truncate">
          {helper}
        </p>
      </div>
      <p className="text-xl font-bold text-foreground shrink-0">{value}</p>
    </div>
  );
}

export function TaskBoardSummary({ summary }: { summary: TaskSummary }) {
  return (
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
      <SummaryCard
        label="Total tasks"
        value={summary.total}
        helper={`${summary.autoGenerated} generated · ${summary.manual} manual`}
        testId="task-board-summary-total"
      />
      <SummaryCard
        label="Active work"
        value={summary.inProgress}
        helper={`${summary.done} completed so far`}
        testId="task-board-summary-active"
      />
      <SummaryCard
        label="Imported backlog"
        value={summary.imported}
        helper="External tasks kept for reconciliation"
        testId="task-board-summary-imported"
      />
      <SummaryCard
        label="Must priority"
        value={summary.mustHave}
        helper="High-priority implementation items"
        testId="task-board-summary-must"
      />
    </div>
  );
}
