"use client";

import { TaskSummary } from "../types";

function SummaryCard({
  label,
  value,
  helper,
}: {
  label: string;
  value: string | number;
  helper: string;
}) {
  return (
    <div className="rounded-2xl border border-border/70 bg-background px-4 py-3 shadow-sm">
      <p className="text-readable-xs uppercase tracking-[0.16em] text-muted-foreground font-medium">
        {label}
      </p>
      <p className="mt-2 text-2xl font-bold text-foreground">{value}</p>
      <p className="mt-1 text-readable-xs text-muted-foreground font-medium">{helper}</p>
    </div>
  );
}

export function TaskBoardSummary({ summary }: { summary: TaskSummary }) {
  return (
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">
      <SummaryCard
        label="Total tasks"
        value={summary.total}
        helper={`${summary.autoGenerated} auto · ${summary.manual} manual`}
      />
      <SummaryCard
        label="Active work"
        value={summary.inProgress}
        helper={`${summary.done} completed so far`}
      />
      <SummaryCard
        label="Must priority"
        value={summary.mustHave}
        helper="High-priority implementation items"
      />
    </div>
  );
}
