"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { db, TaskData, NodeData } from "@/lib/db";
import { generateTasksFromNode, detectDuplicateTasks } from "@/lib/taskEngine";
import {
  GroupingMode,
  StatusFilter,
  PriorityFilter,
  SourceFilter,
  TaskSummary,
} from "../types";

const PRIORITY_ORDER: Record<string, number> = {
  must: 0,
  should: 1,
  could: 2,
  wont: 3,
};

function normalizePriority(priority: TaskData["priority"]) {
  return String(priority).toLowerCase() as PriorityFilter;
}

export function useTaskBoard(node: NodeData) {
  const [tasks, setTasks] = useState<TaskData[]>([]);
  const [nodes, setNodes] = useState<NodeData[]>([]);
  const [isRegenerating, setIsRegenerating] = useState(false);
  const [grouping, setGrouping] = useState<GroupingMode>("feature");
  const [searchQuery, setSearchQuery] = useState("");
  const [statusFilter, setStatusFilter] = useState<StatusFilter>("all");
  const [priorityFilter, setPriorityFilter] = useState<PriorityFilter>("all");
  const [sourceFilter, setSourceFilter] = useState<SourceFilter>("all");
  const [duplicates, setDuplicates] = useState<[number, number, number][]>([]);

  const loadTasks = useCallback(async () => {
    const [projectTasks, projectNodes] = await Promise.all([
      db.tasks.where({ project_id: node.project_id }).toArray(),
      db.nodes.where({ project_id: node.project_id }).toArray(),
    ]);

    const sorted = [...projectTasks].sort((a, b) => {
      // Sort by Tier first (P0 -> P3)
      const tierA = a.priority_tier || "P1";
      const tierB = b.priority_tier || "P1";
      if (tierA !== tierB) return tierA.localeCompare(tierB);

      const priorityA = PRIORITY_ORDER[normalizePriority(a.priority)] ?? 99;
      const priorityB = PRIORITY_ORDER[normalizePriority(b.priority)] ?? 99;

      if (priorityA !== priorityB) return priorityA - priorityB;
      return a.sort_order - b.sort_order;
    });

    setTasks(sorted);
    setNodes(projectNodes);
    setDuplicates(detectDuplicateTasks(sorted));
  }, [node.project_id]);

  useEffect(() => {
    void loadTasks();
  }, [loadTasks]);

  const sourceOptions = useMemo(() => {
    const map = new Map<string, string>();
    nodes.forEach((sn) => map.set(sn.id, sn.label));
    return Array.from(map.entries()).map(([id, label]) => ({ id, label }));
  }, [nodes]);

  const summary = useMemo<TaskSummary>(() => {
    const total = tasks.length;
    const done = tasks.filter((t) => t.status === "done").length;
    const inProgress = tasks.filter((t) => t.status === "in_progress").length;
    const manual = tasks.filter((t) => t.is_manual).length;
    const autoGenerated = total - manual;
    const mustHave = tasks.filter((t) => normalizePriority(t.priority) === "must").length;

    return { total, done, inProgress, manual, autoGenerated, mustHave };
  }, [tasks]);

  const filteredTasks = useMemo(() => {
    const normalizedQuery = searchQuery.trim().toLowerCase();

    return tasks.filter((task) => {
      const sourceNodeLabel = task.source_node_id
        ? (nodes.find((sn) => sn.id === task.source_node_id)?.label ?? "Unknown Source")
        : "Manual Tasks";

      const matchesSearch =
        normalizedQuery.length === 0 ||
        task.title.toLowerCase().includes(normalizedQuery) ||
        task.description.toLowerCase().includes(normalizedQuery) ||
        (task.feature_name || "").toLowerCase().includes(normalizedQuery) ||
        task.group_key.toLowerCase().includes(normalizedQuery) ||
        sourceNodeLabel.toLowerCase().includes(normalizedQuery) ||
        task.labels.some((l) => l.toLowerCase().includes(normalizedQuery));

      const matchesStatus = statusFilter === "all" ? true : task.status === statusFilter;
      const matchesPriority = priorityFilter === "all" ? true : normalizePriority(task.priority) === priorityFilter;
      const matchesSource =
        sourceFilter === "all"
          ? true
          : sourceFilter === "manual"
            ? task.source_node_id === null
            : task.source_node_id === sourceFilter;

      return matchesSearch && matchesStatus && matchesPriority && matchesSource;
    });
  }, [nodes, priorityFilter, searchQuery, sourceFilter, statusFilter, tasks]);

  const updateTask = async (id: string, updates: Partial<TaskData>) => {
    await db.tasks.update(id, {
      ...updates,
      updated_at: new Date().toISOString(),
    });
    await loadTasks();
  };

  const deleteTask = async (id: string) => {
    await db.tasks.delete(id);
    await loadTasks();
  };

  const addManualTask = async () => {
    const now = new Date().toISOString();
    const newTask: TaskData = {
      id: crypto.randomUUID(),
      project_id: node.project_id,
      source_node_id: null,
      title: "New Manual Task",
      description: "",
      group_key: "Manual",
      feature_name: "General",
      priority_tier: "P1",
      priority: "should",
      status: "todo",
      labels: [],
      is_manual: true,
      sort_order: tasks.length,
      created_at: now,
      updated_at: now,
    };
    await db.tasks.add(newTask);
    await loadTasks();
  };

  const regenerateAllTasks = async () => {
    setIsRegenerating(true);
    try {
      const autoTasks = tasks.filter((t) => !t.is_manual);
      await db.tasks.bulkDelete(autoTasks.map((t) => t.id));

      const allContents = await db.nodeContents.toArray();
      const allParsedTasks: TaskData[] = [];
      const now = new Date().toISOString();

      // Collect all tasks from all nodes
      for (const sourceNode of nodes) {
        const content = allContents.find((item) => item.node_id === sourceNode.id);
        if (!content) continue;

        const generated = generateTasksFromNode(sourceNode, content, node.project_id);
        const mapped = generated.map((task, index) => ({
          ...task,
          id: crypto.randomUUID(),
          sort_order: index,
          created_at: now,
          updated_at: now,
        } as TaskData));
        allParsedTasks.push(...mapped);
      }

      // Final insertion
      if (allParsedTasks.length > 0) {
        await db.tasks.bulkAdd(allParsedTasks);
      }
      await loadTasks();
    } finally {
      setIsRegenerating(false);
    }
  };

  return {
    tasks,
    nodes,
    summary,
    filteredTasks,
    isRegenerating,
    grouping,
    setGrouping,
    searchQuery,
    setSearchQuery,
    statusFilter,
    setStatusFilter,
    priorityFilter,
    setPriorityFilter,
    sourceFilter,
    setSourceFilter,
    duplicates,
    sourceOptions,
    updateTask,
    deleteTask,
    addManualTask,
    regenerateAllTasks,
  };
}
