#!/usr/bin/env sh

if ! command -v pnpm >/dev/null 2>&1; then
  echo "❌ Error: pnpm not found in PATH."
  exit 1
fi

echo "Running pre-commit checks..."

echo "Linting..."
pnpm lint || { echo "❌ Lint failed"; exit 1; }

echo "✅ Ready to commit!"
